### ISSUE TITLE
Memory size is exhausted while changes are deployed

### ISSUE THREAD

**Issue by Shadowghost** [Icinga/icingaweb2-module-fileshipper#10]
When trying to import and sync a simple host file (just containing the host block and ip-address) the following error is shown, when deploying the changes:

```
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectImports.php on line 221
```

It is not possible to deploy the changes from activity log nor revoke them. They result in the need of restoring the VM, since re-deploying an older configuration does not reset the changes waiting for deployment.

If logs or anything else is needed, just tell me what you need :)

PS: Not sure if this is fileshipper or director related, feel free to send me over to the other repo ^^

**Comment by Thomas-Gelf** [comment]
Sorry for the late reply,. And no - this is should not be related to fileshipper at all. In case the problem persists please open a related issue in the Director issue tracker with some more details. I could imagine an inheritance loop causing this. Recent optimizations in our template resolving code seem to have caused a short-circuit in our loop prevention code with the result that loops that used to be gracefully detected now being able to hurt you.
