### ISSUE TITLE
Support for Icinga2 conf files/icinga2 objects and templates

### ISSUE THREAD

**Issue by cstegm** [Icinga/icingaweb2-module-fileshipper#12]
I would like to import some configuration files (service templates, host templates...) from different icinga instances to the director.

**Comment by Thomas-Gelf** [comment]
Sorry, I have to refuse this. Icinga 2 does not have a serialize-able configuration "format" but comes with a full blown DSL. If you have running instances I'd suggest to either import from their API or to add a related DB resource and import the required objects and properties from the IDO.
