### ISSUE TITLE
Multiple values in CSV import

### ISSUE THREAD

**Issue by ily4** [Icinga/icingaweb2-module-fileshipper#19]
How to achieve importing host to multiple groups (Group membership)?

Example1:
id, Host, Group1, Group2, Group3
1,"Alpha","g1","g2","g3"
+assignments: 
${Group1} -> groups
${Group2} -> groups
${Group3} -> groups
This works for import (g1, g2, g3 detected as different groups and fields, but Sync job performs only host assignment to latest Group3 [g3]) .

Example2:
id, Host, Group,
1,"Alpha","g1 g2 g3"
+assignment: ${Group} -> groups  
This works for import (g1, g2, g3 detected as different groups, but Sync job performs only host assignment to g3).

Space is valid csv multi-value field separator, but isn't valid for Sync job.

**Comment by Thomas-Gelf** [comment]
Use Example2 and when configuring the Import Source in Director add a Split Property Modifier to the Mix.

**Comment by ily4** [comment]
Thank you very much!
Custom separator (; for example) in Split Property Modifier solved the problem.
