### ISSUE TITLE
Comments starting with '#' are deprecated in ...

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-fileshipper#22]
I receive the following messages when I open in Director the Import Source / Modify Menu which uses the Fileshipper module (fd2c797) - though it also happens with older versions:

```
Deprecated: Comments starting with '#' are deprecated in Unknown on line 1 in /usr/share/php/Icinga/File/Ini/IniParser.php on line 265

Deprecated: Comments starting with '#' are deprecated in Unknown on line 2 in /usr/share/php/Icinga/File/Ini/IniParser.php on line 265

Deprecated: Comments starting with '#' are deprecated in Unknown on line 3 in /usr/share/php/Icinga/File/Ini/IniParser.php on line 265

Deprecated: Comments starting with '#' are deprecated in Unknown on line 4 in /usr/share/php/Icinga/File/Ini/IniParser.php on line 265

Deprecated: Comments starting with '#' are deprecated in Unknown on line 5 in /usr/share/php/Icinga/File/Ini/IniParser.php on line 265

Deprecated: Comments starting with '#' are deprecated in Unknown on line 6 in /usr/share/php/Icinga/File/Ini/IniParser.php on line 265

Deprecated: Comments starting with '#' are deprecated in Unknown on line 7 in /usr/share/php/Icinga/File/Ini/IniParser.php on line 265
```

## Context

The problem is only annoying and not serious, or at least for me the module seems to work fine, it just presents these messages, it would be fine to get rid of them.
I am also not 100% percent sure, that this is related to the fileshipper module, but since it just pops up when I use it, I report it here.

## Your Environment

* icingaweb2-2.5.1-1.el7.icinga.noarch
* icinga2-2.8.4-1.el7.icinga.x86_64
* Director Version (fc58e50)
* RHEL 7.5
* PHP 5.4.16 (/bin/php) and   PHP 7.1.8 (/opt/rh/rh-php71/root/usr/bin/php)

**Comment by Thomas-Gelf** [comment]
Icinga Web 2.5 is strict about comments in INI files. Strictly speaking, `#` is not valid - commented lines must start with a semicolon (`;`). Guess there are lines starting with `#` in your `/etc/icingaweb2/modules/fileshipper/*.ini`

**Comment by swizzly** [comment]
Yeah, that solved the Problem. 
Many thanks!
