### ISSUE TITLE
cannot import/ sync host templates

### ISSUE THREAD

**Issue by plarivee** [Icinga/icingaweb2-module-fileshipper#3]
I don't know if its by design, but cannot seem to be able to sync object_type template. I'm getting errors

This Sync Rule failed when last checked at 2016-11-30 14:44:52: Exception while syncing Icinga\Module\Director\Objects\IcingaHost zone01_template: Sync is not allowed to modify template "zone01_template"

If i remove the sync properties for "object_type", I can create from the file.

**Comment by Thomas-Gelf** [comment]
This used to be an intentional restriction in Director and has been removed either with 1.2.0 or shortly after that. Syncing templates can be tricky, so that's why we had that restriction. However, it should work fine right now.
