### ISSUE TITLE
When imports.ini is misformed the director form fails

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2-module-fileshipper#35]
## Expected Behavior

It should gracefully display an error inside the form, alarming the user the config file should be corrected.

## Current Behavior

Error in UI:

```
array_map(): Expected parameter 2 to be an array, string given
```

## Steps to Reproduce (for bugs)

Broken `/etc/icingaweb2/modules/fileshipper/imports.ini`:
```
xamples]
basedir = "/opt/import"
```

Go to Director any create or modify any fileshipper import.

## Your Environment

* Module version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.8.2
* Icinga 2 version (`icinga2 --version`): 2.12.1
* Operating System and version: CentOS 7
* Webserver, PHP versions: PHP 7.3

**Comment by ACAYspace** [comment]
Try this:

[Samples]
basedir = "/opt/import"
