### ISSUE TITLE
CSV Import use Contains in Assign_filter 

### ISSUE THREAD

**Issue by Simkimdm** [Icinga/icingaweb2-module-fileshipper#8]
Hi,

is it possible to use the contains string while importing Services from csv via the assign_filter attribute?
My CSV:
'apply_name','service_name','assign_where'
'port-channel1','Service-NWC-Interface-Health-extra-Port-Channel','host.vars.monitoring_interfaces contains port-channel1'
I tried "==" as well as "in", but it throws errors.

The normal assignment is like: 
assign where "port-channel1" in host.vars.monitoring_interfaces

Best regards

**Comment by Thomas-Gelf** [comment]
Hi @Simkimdm,

and sorry for the late reply. Setting assign_filter via sync is currently not documented and officially not supported. It should work, as i know from people doing so in a hacky way. We'll definitively document, sharpen and clearly specify an interface for assign_filter's. Please feel free to open a related Director issue as a reminder. In the meantime please forgive me that I'll refuse to document existing hacks. Main reason is that the final API might break those hacks, and I do not want to be held responsible for that ;-)

I'll close this issue so far, as the problem cannot be solved by the fileshipper module.
